services:
  postgres:
    image: postgres:17
    container_name: cas_postgres_dev
    restart: always
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - cas_postgres_dev_data:/var/lib/postgresql/data

volumes:
  cas_postgres_dev_data: