"""create supplemental materials table

Revision ID: 92e0ec5a21d5
Revises: 720893fe03fc
Create Date: 2026-06-12 12:31:43.048089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e0ec5a21d5'
down_revision: Union[str, Sequence[str], None] = '720893fe03fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplemental_materials',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('material_type', sa.Enum('PDF', 'IMAGE', 'OFFICE', name='material_type'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplemental_materials_id'), 'supplemental_materials', ['id'], unique=False)
    op.create_index(op.f('ix_supplemental_materials_lesson_id'), 'supplemental_materials', ['lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplemental_materials_lesson_id'), table_name='supplemental_materials')
    op.drop_index(op.f('ix_supplemental_materials_id'), table_name='supplemental_materials')
    op.drop_table('supplemental_materials')
    # ### end Alembic commands ###
