from enum import Enum


class RoleName(str, Enum):
    ADMIN = "ADMIN"
    INSTRUCTOR = "INSTRUCTOR"
    STUDENT = "STUDENT"


class CourseStatus(str, Enum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    HIDDEN = "HIDDEN"
    FINISHED = "FINISHED"


class CourseLevel(str, Enum):
    BEGINNER = "BEGINNER"
    INTERMEDIATE = "INTERMEDIATE"
    ADVANCED = "ADVANCED"


class MaterialType(str, Enum):
    PDF = "PDF"
    IMAGE = "IMAGE"
    OFFICE = "OFFICE"


class QuestionType(str, Enum):
    MULTIPLE_CHOICE = "MULTIPLE_CHOICE"
    TRUE_FALSE = "TRUE_FALSE"


class AttemptStatus(str, Enum):
    IN_PROGRESS = "IN_PROGRESS"
    SUBMITTED = "SUBMITTED"


class AuditAction(str, Enum):
    LOGIN = "LOGIN"
    LOGIN_FAILED = "LOGIN_FAILED"
    COURSE_CREATED = "COURSE_CREATED"
    COURSE_PUBLISHED = "COURSE_PUBLISHED"
    COURSE_HIDDEN = "COURSE_HIDDEN"
    ENROLLMENT_CREATED = "ENROLLMENT_CREATED"
    CERTIFICATE_ISSUED = "CERTIFICATE_ISSUED"
    PASSWORD_CHANGED = "PASSWORD_CHANGED"
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"